# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-05 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=11)),
                ('tipo_servicio', models.CharField(choices=[('Duplicado_Carnet', 'Duplicado de carnet: valor $5.000'), ('Duplicado_Constancias', 'Duplicado de constancias: valor $4.100'), ('Duplicado_Actas', 'Duplicado de actas de grado: valor $4.100'), ('Duplicado_Certificados', 'Duplicado de certificados: valor $4.100'), ('Contenidos_Programaticos', 'Contenidos program\xe1ticos: valor $4.100')], max_length=100)),
                ('status_admin', models.BooleanField(default=False)),
                ('status_user', models.BooleanField(default=False)),
                ('codigo', models.CharField(default=True, max_length=100)),
            ],
        ),
    ]
